//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34209
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCompany("BitTacklr")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2014, BitTacklr. All rights reserved.")]
[assembly: System.Reflection.AssemblyProduct("AggregateSource")]
[assembly: System.Reflection.AssemblyTrademark("AggregateSource is a trademark of BitTacklr")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]


