//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCompany("BitTacklr")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2014, BitTacklr. All rights reserved.")]
[assembly: System.Reflection.AssemblyProduct("AggregateSource")]
[assembly: System.Reflection.AssemblyTrademark("AggregateSource is a trademark of BitTacklr")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]


